### ISSUE TITLE
PIP install fails

### ISSUE THREAD

**Issue by sandy-m** [watchforstock/evohome-client#27]
Hi,
Thank you for this. I Installed it a few months ago on a Raspberry Pi and it's been working great. Just tried to install on a new Raspberry Pi and the pip install fails:

pip install ./evohome-client

Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 269, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 173, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 71, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2793, in parse
    reqs = list(parse_requirements(s))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2721, in parse_requirements
    "version spec")
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2686, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', './evohome-client', 'at', '/evohome-client')

Can you help resolve this?
Other pip installs work.
Is there anything I should do before running the pip install?
Thanks for any help

**Comment by watchforstock** [comment]
Hi,
Instead of downloading the source and installing it, try just running "pip install evohomeclient" and that should download and install it in one go. I'd be interested if that command has the same problem
Thanks

**Comment by sandy-m** [comment]
Thanks for the quick response
sudo pip install evohomeclient - worked first time.
Many thanks
